const numero1 = document.querySelector('numero1')
const numero2 = document.querySelector('numero2')
const btnCalcular = document.querySelector('#btnCalcular')
const app = document.querySelector('app')
const resultado = document.querySelector('resultado')
const soma = document.querySelector('soma')
const subtracao = document.querySelector('subtritacao')
const multiplicacao = document.querySelector('multiplicacao')
const divisao = document.querySelector('divisao')
alert('numero1')